Change the directory structure, fix some tips

diff --git a/redos_autorun/runtest b/redos_autorun/runtest
--- a/redos_autorun/runtest
+++ b/redos_autorun/runtest
@@ -1,10 +1,11 @@
 #!/bin/bash
 
 #
-# Program:
+# Description:
 # 	This program can autorun virt-test testcases
 #
-# 
+# Version: 0.5 
+# Designed by: Ming.Li
 #
 
 
@@ -15,7 +16,7 @@ DEFAULT_TESTS_DIR=$CURRENT_DIR/tests/
 DEFAULT_MODULE_LIST=$CURRENT_DIR/tests/modules_list
 DEFAULT_MODULE_FILE_DIR=$CURRENT_DIR/tests/
 DEFAULT_SCATTERED_LIST=$CURRENT_DIR/tests/scattered_list
-
+MODE="ANALYSIS"
 
 get_config_key()
 {    
@@ -57,8 +58,7 @@ debug()
 	echo -e "\t\tDEFAULT_SCATTERED_LIST = $DEFAULT_SCATTERED_LIST"
 	echo -e "\t\tCURRENT_CASESLIST_FILE = $CURRENT_CASESLIST_FILE"
 	echo -e "\t\tCURRENT_LOG_FILE = $CURRENT_LOG_FILE"
-	echo -e "\t\tCURRENT_RUN_FILE = $CURRENT_RUN_FILE"
-	echo -e "\t\tCURRENT_DETAIL_LOG_FILE = $CURRENT_RUN_FILE"
+	echo -e "\t\tCURRENT_DETAIL_LOG_FILE = $CURRENT_DETAIL_LOG_FILE"
 
 	# print config data
 	echo -e "\tConfig:"
@@ -70,29 +70,6 @@ debug()
 	echo -e "\n"
 }
 
-#usage()
-#{
-#    cat <<-EOF >&2
-
-#    usage: ${0##*/} [ -a EMAIL_TO ] [ -c NUM_PROCS ] [ -C FAILCMDFILE ] [ -T TCONFCMDFILE ]
-#    [ -d TMPDIR ] [ -D NUM_PROCS,NUM_FILES,NUM_BYTES,CLEAN_FLAG ] -e [ -f CMDFILES(,...) ]
-#    [ -g HTMLFILE] [ -i NUM_PROCS ] [ -l LOGFILE ] [ -m NUM_PROCS,CHUNKS,BYTES,HANGUP_FLAG ]
-#    -N -n [ -o OUTPUTFILE ] -p -q [ -r LTPROOT ] [ -s PATTERN ] [ -t DURATION ]
-#    -v [ -w CMDFILEADDR ] [ -x INSTANCES ] [ -b DEVICE ] [-B LTP_DEV_FS_TYPE]
-#        [ -F LOOPS,PERCENTAGE ] [ -z BIG_DEVICE ] [-Z  LTP_BIG_DEV_FS_TYPE]
-#
-#    -a EMAIL_TO     EMAIL all your Reports to this E-mail Address
-#    -c NUM_PROCS    Run LTP under additional background CPU load
-#                    [NUM_PROCS = no. of processes creating the CPU Load by spinning over sqrt()
-#                                 (Defaults to 1 when value)]
-#    -C FAILCMDFILE  Command file with all failed test cases.
-#    -T TCONFCMDFILE Command file with all test cases that are not fully tested.
-#    -f CMDFILES     Execute user defined list of testcases (separate with ',')
-#    example: ${0##*/} -c 2 -i 2 -m 2,4,10240,1 -D 2,10,10240,1 -p -q  -l /tmp/result-log.$$ -o /tmp/result-output.$$ -C /tmp/result-failed.$$ -d ${PWD}
-#
-#
-#	exit 0
-#}
 
 merge_params()
 {
@@ -188,7 +165,7 @@ set_testcases_to_list()
 #This function is v0.1
 		extra_params="$extra_params"" ""$2"" "
 
-#This function is next version.
+#This function is next version. It can resolve repeated parameters
 #		if [ ! -z "$extra_params" ] || [ ! -z "$2" ]; then
 #			merge_params "$extra_params" "$2"
 #		fi
@@ -202,25 +179,6 @@ set_testcases_to_list()
 			echo -e "$3"":""$testcase_name"" {""$extra_params"" ""$DEFAULT_EXTRA_COMMAND"" ""$LIBVIRT_EXTRA_COMMAND""}" >> $CURRENT_CASESLIST_FILE
 		fi	
 	done
-}
-
-init_file()
-{
-	if [ ! -d "$CURRENT_LOG_PATH" ]; then
-		mkdir $CURRENT_LOG_PATH
-	fi
-
-	if [ ! -f "$CURRENT_CASESLIST_FILE" ]; then
-		touch $CURRENT_CASESLIST_FILE
-	fi
-
-	if [ ! -f "$CURRENT_LOG_FILE" ]; then
-		touch $CURRENT_LOG_FILE
-	fi
-
-	if [ ! -f "$CURRENT_DETAIL_LOG_FILE" ]; then
-		touch $CURRENT_DETAIL_LOG_FILE
-	fi
 }
 
 
@@ -250,8 +208,6 @@ init_testcase_list()
 			module_extra_params=`echo $ml_line | cut -d '{' -f2 | cut -d '}' -f1`
 			module_extra_params=`echo $module_extra_params`
 		fi
-		echo -e "\tModule $module_count: $class:$module_name    module_params:$module_extra_params"
-		module_count=$(($module_count+1))
 
 		if [ -z "$module_name" ]; then
 			echo "ERROR: Modules name is not set($module_name)"
@@ -263,12 +219,25 @@ init_testcase_list()
 			exit 2
 		fi
 
-		if [ ! -f "$module_file" ]; then
-			echo "ERROR: Don\`t have testcases file($module_file)"
-			exit 3
+		if [ "$MODE" = "DIRECT" ]; then
+			echo -e "\t\tcase $module_count: $module_name $module_extra_params"
+			if [ "$class" = "qemu" ] || [ "$class" = "QEMU" ]; then
+				echo -e "$class"":""$module_name"" {""$module_extra_params"" ""$DEFAULT_EXTRA_COMMAND"" ""$QEMU_EXTRA_COMMAND""}" >> $CURRENT_CASESLIST_FILE
+			fi
+
+			if [ "$class" = "libvirt" ] || [ "$class" = "LIBVIRT" ]; then
+				echo -e "$class"":""$module_name"" {""$module_extra_params"" ""$DEFAULT_EXTRA_COMMAND"" ""$LIBVIRT_EXTRA_COMMAND""}" >> $CURRENT_CASESLIST_FILE
+			fi
 		else
-			set_testcases_to_list "$module_file" "$module_extra_params" "$class"
+			printf "\tModule $module_count: %-40s\t%-60s\n" "$class:$module_name" "module_params:$module_extra_params"
+			if [ ! -f "$module_file" ]; then
+				echo "ERROR: Don\`t have testcases file($module_file)"
+				exit 3
+			else
+				set_testcases_to_list "$module_file" "$module_extra_params" "$class"
+			fi
 		fi
+		module_count=$(($module_count+1))
 	done
 }
 
@@ -286,17 +255,16 @@ generate_cmd()
 	
 	if [ "$class" = "qemu" ] || [ "$class" = "QEMU" ]; then
 		cmd="$VIRTTEST_DIR""$DEFAULT_RUN_COMMAND"" ""$params"" ""--tests"" ""$testcase_name"" ""-v"
-	fi
-
-	if [ "$class" = "libvirt" ] || [ "$class" = "LIBVIRT" ]; then
+	elif [ "$class" = "libvirt" ] || [ "$class" = "LIBVIRT" ]; then
 		cmd="$VIRTTEST_DIR""$DEFAULT_RUN_COMMAND"" ""$params"" ""--tests"" ""$testcase_name"" ""-v"
+	else
+		echo "1"
 	fi	
 	echo "$cmd"
 }
 
 run_test()
 {
-	testcase_count=1
 	cat $CURRENT_CASESLIST_FILE | while read tc_line
 	do
 		class=""
@@ -308,33 +276,36 @@ run_test()
 			params=`echo $tc_line | cut -d '{' -f2 | cut -d '}' -f1`
 			params=`echo $params`
 		fi
-		echo -e "$testcase_count. $class:$testcase_name    \c"
+		printf "%-150s" "$testcase_count. $class:$testcase_name"
 		run_cmd=`generate_cmd "$class" "$testcase_name" "$params"`
-		if [ "$?" = "1" ]; then
+		if [ "$run_cmd" = "1" ]; then
 			echo -e "\033[34m SKIP(autorun: Parameter error)  \033[0m"
-			echo -e "SKIP: $class:$testcase_name (autorun: Parameter error)" >> "CURRENT_LOG_FILE"
+			echo -e "SKIP\t$class:$testcase_name (autorun: Parameter error)" >> "CURRENT_LOG_FILE"
+			skip_count=$(($skip_count+1))
 		else
-			#${run_cmd} 2>>"$CURRENT_DETAIL_LOG_FILE" 1>>"$CURRENT_DETAIL_LOG_FILE"
 			result=`${run_cmd}  2>>"$CURRENT_DETAIL_LOG_FILE" | grep -E "PASSED|FAILED|SKIPPED"`
 			PASS=`echo "$result" | grep "PASSED: " | awk -F'PASSED: ' '{print $2}'`
 			FAIL=`echo "$result" | grep "FAILED: " | awk -F'FAILED: ' '{print $2}'`
 			SKIP=`echo "$result" | grep "SKIPPED: " | awk -F'SKIPPED: ' '{print $2}'`
 			if [ "$PASS" = "1" ]; then
-				echo -e "\033[32m PASS \033[0m"
-				echo -e "PASS: $class:$testcase_name" >> "$CURRENT_LOG_FILE"
+				printf "\033[32m %-20s \033[0m\n" "PASS"
+				echo -e "PASS\t$class:$testcase_name" >> "$CURRENT_LOG_FILE"
+				pass_count=$(($pass_count+1))
 			fi
 
 			if [ "$FAIL" = "1" ]; then
-				echo -e "\033[31m  FAIL \033[0m"
-				echo -e "FAIL: $class:$testcase_name" >> "$CURRENT_LOG_FILE"
+				printf "\033[31m %-20s \033[0m\n" "FAIL"
+				echo -e "FAIL\t$class:$testcase_name" >> "$CURRENT_LOG_FILE"
+				fail_count=$(($fail_count+1))
 			fi	
 			
 			if [ "$SKIP" = "1" ]; then
-				echo -e "\033[34m SKIP  \033[0m"
-				echo -e "SKIP: $class:$testcase_name" >> "$CURRENT_LOG_FILE"
+				printf "\033[34m %-20s \033[0m\n" "SKIP"
+				echo -e "SKIP\t$class:$testcase_name" >> "$CURRENT_LOG_FILE"
+				skip_count=$(($skip_count+1))
 			fi	
 		fi
-		testcase_count=$(($testcase_count+1))
+		((testcase_count++))
 	done
 }
 
@@ -347,11 +318,38 @@ init_env_params()
 	CURRENT_DETAIL_LOG_FILE="$CURRENT_LOG_PATH""detail_log"
 }
 
+init_file()
+{
+	
+	if [ ! -d "$DEFAULT_LOG_DIR" ]; then
+		mkdir "$DEFAULT_LOG_DIR"
+	fi
+	
+	if [ ! -d "$CURRENT_LOG_PATH" ]; then
+		mkdir $CURRENT_LOG_PATH
+	fi
+
+	if [ ! -f "$CURRENT_CASESLIST_FILE" ]; then
+		touch $CURRENT_CASESLIST_FILE
+	fi
+
+	if [ ! -f "$CURRENT_LOG_FILE" ]; then
+		touch $CURRENT_LOG_FILE
+	fi
+
+	if [ ! -f "$CURRENT_DETAIL_LOG_FILE" ]; then
+		touch $CURRENT_DETAIL_LOG_FILE
+	fi
+}
+
 init()
 {
 	init_env_params
 	init_file
 }
+
+
+
 
 main()
 {
@@ -366,6 +364,49 @@ main()
 }
 
 
+usage()
+{
+	echo -e "Usage: runtest [Options]"
+	echo -e ""
+	echo -e "Options:"
+	printf "\t%-40s%-20s\n" "-h" "Show this help message and exit"
+	printf "\t%-40s%-20s\n" "-m <modules_list_file>" "Use custom modules_list.        Default: ./tests/modules_list"
+	printf "\t%-40s%-20s\n" "-t <testcases_list_file>" "Only run testcase in this file."
+#	echo -e "\t-h\t\t\tshow this help message and exit"
+#	echo -e "\t-m  <modules_list_file>\t\tUse custom modules_list.\tDefault: ./tests/modules_list"
+#	echo -e "\t-t  <testcases_list_file>\t\tOnly run testcases in this file.\tDefault: ./tests/modules_list"
+	exit 0
+}
+
 # Start in here
+
+while getopts "hm:t:" arg 
+do
+	case $arg in
+		h)
+			usage
+			;;
+		m)
+			if [ ! -f "$OPTARG" ]; then
+				echo -e "$OPTARG is not exist."
+				exit 1
+			fi
+			DEFAULT_MODULE_LIST="$OPTARG"	
+			;;
+		t)
+			if [ ! -f "$OPTARG" ]; then
+				echo -e "$OPTARG is not exist."
+				exit 1
+			fi
+			MODE="DIRECT"	
+			DEFAULT_MODULE_LIST="$OPTARG"	
+			;;
+		?)
+			echo "unkonw argument"
+			usage
+        		;;
+        esac
+done
+
 main
 
